[package]
name = "stackyard"
version = "0.1.0"
edition = "2024"
description = "Stack based data structures and algorithms"
license = "AGPL-3.0-only"
readme = "README.md"
repository = "https://git.colorized.life/stackyard"
keywords = ["no_std", "data-structures", "no-heap", "embedded"]
categories = ["data-structures", "no-std"]
exclude = ["/.gitignore"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["alloc"]
alloc = []

[dependencies]

[profile.dev.package."*"]
opt-level = 1
debug = false

[profile.release]
lto = true
codegen-units = 1
strip = true


