[package]
name = "stackyard"
version = "0.2.2"
edition = "2024"
description = "Freestanding data structures and algorithms"
license = "AGPL-3.0-only"
readme = "README.md"
repository = "https://git.colorized.life/stackyard"
keywords = ["no_std", "data-structures", "no-heap", "embedded", "algorithms"]
categories = ["data-structures", "no-std"]
exclude = ["/.github", "/scripts", "/.gitignore"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["alloc"]
alloc = []

[dependencies]

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "stack_vs_vec"
harness = false

[profile.dev.package."*"]
opt-level = 1
debug = false

[profile.release]
lto = true
codegen-units = 1
strip = true
